trigger:
- master  # o la rama que uses

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'AzureStudentJordi'  # Tu Service Connection
  appName: 'myappservice1234-jmb'        # Nombre del App Service
  resourceGroup: 'rg-myapp'               # Resource Group donde está el App Service

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python --version
    where python
  displayName: 'Check Python version and path'

- script: |
    python -m pip install --upgrade pip
    pip install -r app/requirements.txt  # Ruta si tenés requirements en carpeta app
  displayName: 'Instalar dependencias'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'app'   # Carpeta donde está el código fuente
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flask_app.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webApp'          # Windows App Service
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/flask_app.zip'
